pipeline:

# =======================================
# Setup  ================================
# =======================================
  install:
    image: node:carbon
    commands:
      - yarn install --frozen-lockfile
    when:
      event: [ pull_request , tag ]

# =======================================
# Tests =================================
# =======================================
  test-lint:
    image: node:carbon
    group: test
    commands:
      - yarn test:lint
    when:
      event: [ pull_request , tag ]

# =======================================
# Tags Creation =========================
# =======================================
  # Build release
  build-release:
    image: node:carbon
    commands:
      - npm install --global gatsby-cli@1.1.58
      - rm -rf .cache public
      - gatsby build --prefix-paths
    when:
      event: [tag]

  # Package release build
  package-release:
    group: packaging
    image: fpfis/php56-dev
    commands:
      - tar -czC public -f full-${DRONE_REPO_NAME}-${DRONE_TAG}.tar.gz .
    when:
      event: [tag]
      
  # Push release to Github
  push-github-release:
    image: plugins/github-release
    files:
      - full-${DRONE_REPO_NAME}-${DRONE_TAG}.tar.gz
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
    secrets: [ GITHUB_RELEASE_API_KEY ]
    when:
      event: [tag]
      
  # Trigger deploy event on Github
  create-deploy-production:
    image: fpfis/drone-plugin-github-deploy
    state: create
    deploy_environment: production
    secrets: [ github_api_token ]
    automerge: false
    when:
      event: [tag]
    
# =======================================
# Deployment ============================
# =======================================

  # Download release from github and extract into build folder
  download-github-release:
    image: instrumentisto/rsync-ssh
    commands:
      - wget https://github.com/ec-europa/digitec/releases/download/${DRONE_TAG}/full-${DRONE_REPO_NAME}-${DRONE_TAG}.tar.gz
      - wget https://github.com/ec-europa/digitec/releases/download/${DRONE_TAG}/sha1sum.txt
      - sha1sum -c sha1sum.txt
      - mkdir build
      - tar zxvf full-${DRONE_REPO_NAME}-${DRONE_TAG}.tar.gz -C build
      - echo $(date +%s) > build/.timestamp
      - echo "${DRONE_COMMIT_SHA}" > build/.commit
    when:
      event: deployment

  # Deploy build folder into production
  deploy-to-production:
    image: instrumentisto/rsync-ssh
    secrets: [ MGMT_IP, MGMT_KEY, MGMT_DIGITEC_PATH ]
    commands:
      - echo "$MGMT_KEY" > /deploy.key
      - chmod 600 /deploy.key
      - rsync -avz --delete-after --progress -e "ssh -i /deploy.key -o StrictHostKeyChecking=no" build fpfis@$MGMT_IP:$MGMT_DIGITEC_PATH
      #- ssh -o StrictHostKeyChecking=no -i /deploy.key fpfis@$MGMT_IP git -C "$MGMT_DIGITEC_PATH" add -A .
      #- ssh -o StrictHostKeyChecking=no -i /deploy.key fpfis@$MGMT_IP git -C "$MGMT_DIGITEC_PATH" commit -m"Deployed ${DRONE_REPO_ORG}/${DRONE_REPO_NAME}@${DRONE_TAG} from drone build ${DRONE_BUILD_NUMBER}."
      #- ssh -o StrictHostKeyChecking=no -i /deploy.key fpfis@$MGMT_IP git -C "$MGMT_DIGITEC_PATH" git  push 'nas-reference' 'master'
    when:
      event: deployment
  
