pipeline:
  install:
    image: node:carbon
    commands:
      - yarn install --frozen-lockfile

  test-lint:
    image: node:carbon
    group: test
    commands:
      - yarn test:lint

  build-release:
    image: node:carbon
    commands:
      - npm install --global gatsby-cli
      - rm -rf .cache public
      - gatsby build --prefix-paths
