pipeline:
  install:
    image: node:carbon
    commands:
      - yarn install --frozen-lockfile

  test-lint:
    image: node:carbon
    group: test
    commands:
      - yarn test:lint

  # Build release
  build-release:
    image: node:carbon
    commands:
      - npm install --global gatsby-cli@1.1.58
      - rm -rf .cache public
      - gatsby build --prefix-paths
    event: [tag]

  # Package release build
  package-full:
    group: packaging
    image: fpfis/php56-dev
    commands:
      - tar -czC public -f full-${DRONE_REPO_NAME}-${DRONE_TAG}.tar.gz .
    when:
      event: [tag]
      
  # Push release to Github
  github_release:
    image: plugins/github-release
    files:
      - full-${DRONE_REPO_NAME}-${DRONE_TAG}.tar.gz
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
    secrets: [ GITHUB_RELEASE_API_KEY ]
    when:
      event: [tag]
      
  # Trigger deploy event on Github
  create-deploy-production:
      image: fpfis/drone-plugin-github-deploy
      state: create
      deploy_environment: production
      secrets: [ github_api_token ]
      automerge: false
      when:
        event: [tag]
        
  # Deploy release on production   
  # - Download tar.gz
  # - rsync to mgmt
  # - gacp (git add, commit, push)
