backend:
  name: git-gateway
  branch: master
  squash_merges: true
  commit_messages:
    create: 'feat({{collection}}): create {{collection}} “{{slug}}”'
    update: 'feat({{collection}}): update {{collection}} “{{slug}}”'
    delete: 'feat({{collection}}): delete {{collection}} “{{slug}}”'
    uploadMedia: 'feat(media): upload “{{path}}”'
    deleteMedia: 'feat(media): delete “{{path}}”'

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "speakers"
    label: "Speakers"
    label_singular: "Speaker"
    folder: "data/speakers"
    extension: md
    create: true
    slug: "{{firstname}}-{{lastname}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "speaker"}
      - {label: "Firstname", name: "firstname", widget: "string"}
      - {label: "Lastname", name: "lastname", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Twitter handle", name: "twitter", widget: "string"}
      - {label: "Picture", name: "picture", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "data/events"
    extension: md
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Start", name: "starts", widget: "string"}
      - {label: "Ends", name: "ends", widget: "string"}
      - {label: "Venue", name: "venue", widget: "string"}
      - {label: "Color", name: "color", widget: "string", default: "grey"}
      - {label: "Register", name: "register", widget: "boolean", default: false}
      - label: "Speakers"
        name: "speakers"
        widget: "list"
        fields:
          - {label: "Speaker", name: "speaker", widget: "relation", collection: "speakers", searchFields: ["firstname", "lastname"], displayFields: ["firstname", "lastname"],valueField: "lastname"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "stands"
    label: "Stands"
    label_singular: "Stand"
    folder: "data/stands"
    extension: md
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "stand"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Number", name: "number", widget: "string"}
      - {label: "Visual", name: "visual", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "homepage"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "homepage"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
