backend:
  name: git-gateway
  branch: master
  squash_merges: true
  commit_messages:
    create: 'feat({{collection}}): create {{collection}} “{{slug}}”'
    update: 'feat({{collection}}): update {{collection}} “{{slug}}”'
    delete: 'feat({{collection}}): delete {{collection}} “{{slug}}”'
    uploadMedia: 'feat(media): upload “{{path}}”'
    deleteMedia: 'feat(media): delete “{{path}}”'

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "speakers"
    label: "Speakers"
    label_singular: "Speaker"
    folder: "data/speakers"
    extension: md
    create: true
    slug: "{{firstname}}-{{lastname}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "speaker"}
      - {label: "Firstname", name: "firstname", widget: "string"}
      - {label: "Lastname", name: "lastname", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Twitter handle", name: "twitter", widget: "string", required: false}
      - {label: "Picture", name: "picture", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "data/events"
    extension: md
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Start", name: "starts", widget: "datetime", format: "HH:mm"}
      - {label: "Ends", name: "ends", widget: "datetime", format: "HH:mm"}
      - {label: "Venue", name: "venue", widget: "string", required: false}
      - {label: "Color", name: "color", widget: "select", default: "grey", options: ["none", "grey", "blue", "purple", "yellow"]}
      - {label: "Register", name: "register", widget: "boolean", default: false}
      - label: "Speakers"
        name: "speakers"
        widget: "list"
        default: []
        required: false
        fields:
          - {label: "Speaker", name: "speaker", widget: "relation", collection: "speakers", searchFields: ["firstname", "lastname"], displayFields: ["firstname", "lastname"],valueField: "lastname"}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "stands"
    label: "Stands"
    label_singular: "Stand"
    folder: "data/stands"
    extension: md
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "stand"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Number", name: "number", widget: "string"}
      - {label: "Picture", name: "picture", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "homepage"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "homepage"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: markdown}
      - file: "src/pages/practical.md"
        label: "Practical"
        name: "practical"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "practical-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
